################################################################################
# Function that takes a distinctive features array and returns a dissimilarity 
# matrix for all stimuli in an experiment. This measure is based on  Lee and 
# Navarro 2002, equation 12.
################################################################################


# This function takes two arguments:
#   1: saliency, vector of size N (number of features) with the weighting  
#      assigned to each feature dimension.
#   2: distinctive_features, distinctive features array generated by the
#      function in `lee-navarro-distinctive.R`

featural_distance <- function(saliency, distinctive_features){
  
  n_features <- dim(distinctive_features$in_i_not_in_j)[2]
  n_stimulus <- dim(distinctive_features$in_i_not_in_j)[3]
  
  if(missing(saliency)){
    saliency <- rep(x = 1 / n_features, times = n_features)
  }
  
  stopifnot(exprs = 
              length(saliency) == dim(distinctive_features$in_i_not_in_j)[2])
  
  ftd_ij <- 
    t(apply(X = distinctive_features$in_i_not_in_j, MARGIN = 3, 
                    saliency, FUN = "%*%")) + 
    t(apply(X = distinctive_features$not_in_i_in_j, MARGIN = 3, 
                                                    saliency, FUN = "%*%"))
  
  return(ftd_ij)
}
