# Function takes the posterior predictive samples generated by the chmm 
# posterior predictive sampler and reduces it to a mean vector for each 
# participant (rows) and stimulus (columns)

posterior_predictive_mean <- function (n_iter, data_path, features_path, 
                                       samples_path, transfer_id) {
  
  data <- readr::read_csv(file = data_path)
  
  n_stimulus <- max(unique(data$stimulus))
  
  participants <- unique(data$id)
  
  transfer_trial <- unique(data$trial_condition[which(data$condition_char == "transfer")])
  
  features <- readr::read_csv(file = features_path)
  
  stimulus_distance <- minkowski_distance(stimulus_features = features, p = 1)
  
  stimulus_similarity <- similarity_ij(decay_rate = 1, decay_function = 1, 
                                       dissimilarity = stimulus_distance)
  
  samples <- readRDS(file = samples_path)
  
  count <- 0
  
  output <- list()
  
  output$y_hat <- matrix(data = NA, nrow = length(participants), ncol = n_stimulus)
  
  for (pp in participants) {
    count <- count + 1
    post_pred <- posterior_predictive(iterations = n_iter, posterior = samples, 
                                      similarity = stimulus_similarity, 
                                      trial = (transfer_trial[transfer_id] - 1), 
                                      participant_id = pp)
    
    output$y_hat[count, ] <- rowMeans(post_pred$y_hat)
  }
  
  saveRDS(object = output, 
          file = paste(c("data/posterior-samples/posterior-predictive-bartlema-diagonal/chmm-transfer-", 
                         transfer_id, 
                         ".rds"), collapse = ""))
}
